// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdminLTE.Models
{
    public partial class Audit
    {
        public Guid Guid { get; set; }
        [Column("audit_datetime_utc")]
        public DateTime AuditDatetimeUtc { get; set; }
        [Required]
        [Column("audit_type")]
        [StringLength(50)]
        public string AuditType { get; set; }
        [Column("audit_user")]
        [StringLength(100)]
        public string AuditUser { get; set; }
        [Column("table_name")]
        [StringLength(150)]
        public string TableName { get; set; }
        [Column("key_values")]
        [StringLength(250)]
        public string KeyValues { get; set; }
        [Column("old_values")]
        public string OldValues { get; set; }
        [Column("new_values")]
        public string NewValues { get; set; }
        [Column("changed_columns")]
        public string ChangedColumns { get; set; }
        [Key]
        [Column("ID")]
        public int Id { get; set; }
    }
}