// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdminLTE.Models
{
    public partial class UserAuditEvents
    {
        [Key]
        public int UserAuditId { get; set; }
        public int AuditEvent { get; set; }
        public string IpAddress { get; set; }
        public DateTimeOffset Timestamp { get; set; }
        [Required]
        public string UserId { get; set; }
    }
}